services:
  web:
    build: .
    container_name: meu-projeto-web
    ports:
      - "8082:80"      # Mudei para 8082 para evitar conflito com Jenkins (8085) e outro web (8080)
    volumes:
      - /home/joao-victor/my_web_pages/AgendaTelefonica/src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: meu-projeto-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agenda
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3307:3306"    # Mudei para 3307 para evitar conflito com Jenkins ou outros MySQL
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: meu-projeto-phpmyadmin
    restart: always
    ports:
      - "8083:80"      # Mudei para 8083 para n√£o conflitar com web ou Jenkins
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
